spring:
  application:
    name: club
  config:
    import:
      - optional:classpath:./secret/db.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security.web: trace
    dev.example: debug